In [1]:
import numpy as np, pandas as pd

In [15]:
from pandas import Series, DataFrame

In [3]:
import webbrowser as wb
website='https://en.wikipedia.org/wiki/NFL_win%E2%80%93loss_records'
wb.open(website)

True

In [5]:
nfl_frame=pd.read_clipboard() # Will return an error as shown. The solution is copy the contents to a text editor and then call this function

CParserError: Error tokenizing data. C error: Expected 11 fields in line 5, saw 12

### To eliminate the above error, Copy the web content to a text editor like notepad and then copy from notepad to the clipboard and then execute thhis command again

In [7]:
nfl_frame=pd.read_clipboard()

In [8]:
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Dallas Cowboys,511,378,6,0.574,1960,894,NFC East
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North
5,6,San Francisco 49ers,545,444,14,0.550,1950,1003,NFC West
6,7,New England Patriots,478,395,9,0.547,1960,882,AFC East
7,8,New York Giants,691,581,33,0.542,1925,1305,NFC East
8,9,Denver Broncos,464,400,10,0.537,1960,874,AFC West
9,10,Minnesota Vikings,457,401,10,0.532,1961,868,NFC North
10,11,Oakland Raiders,462,406,11,0.532,1960,879,AFC West
11,12,Indianapolis Colts,508,448,7,0.531,1953,963,AFC South
12,13,Pittsburgh Steelers,618,561,21,0.524,1933,1200,AFC North
13,14,Kansas City Chiefs,432,415,12,0.510,1960,859,AFC West
14,15,Washington Redskins,592,576,27,0.507,1932,1195,NFC East
15,16,Cleveland Browns,469,458,10,0.506,1950,937,AFC North
16,17,San Diego Chargers,428,425,11,0.502,1960,864,AFC West
17,18,St. Louis Rams,552,555,21,0.499,1937,1128,NFC West
18,19,Seattle Seahawks,319,320,0,0.499,1976,639,NFC West
19,20,Philadelphia Eagles,560,594,26,0.486,1933,1180,NFC East

In [9]:
nfl_frame.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied*', u'Pct.', u'First Season',
       u'Total Games', u'Conference'],
      dtype='object')

In [11]:
nfl_frame.Team

0           Dallas Cowboys
1            Chicago Bears
2        Green Bay Packers
3           Miami Dolphins
4         Baltimore Ravens
5      San Francisco 49ers
6     New England Patriots
7          New York Giants
8           Denver Broncos
9        Minnesota Vikings
10         Oakland Raiders
11      Indianapolis Colts
12     Pittsburgh Steelers
13      Kansas City Chiefs
14     Washington Redskins
15        Cleveland Browns
16      San Diego Chargers
17          St. Louis Rams
18        Seattle Seahawks
19     Philadelphia Eagles
Name: Team, dtype: object

In [12]:
nfl_frame.First Season

SyntaxError: invalid syntax (<ipython-input-12-02fa85f00681>, line 1)

In [13]:
nfl_frame['First Season']

0     1960
1     1920
2     1921
3     1966
4     1996
5     1950
6     1960
7     1925
8     1960
9     1961
10    1960
11    1953
12    1933
13    1960
14    1932
15    1950
16    1960
17    1937
18    1976
19    1933
Name: First Season, dtype: int64

### Grabbing some columns from the dataframe

In [16]:
DataFrame(nfl_frame,columns=['Team','First Season','Total Games'])

                    Team  First Season  Total Games
0         Dallas Cowboys          1960          894
1          Chicago Bears          1920         1357
2      Green Bay Packers          1921         1339
3         Miami Dolphins          1966          792
4       Baltimore Ravens          1996          326
5    San Francisco 49ers          1950         1003
6   New England Patriots          1960          882
7        New York Giants          1925         1305
8         Denver Broncos          1960          874
9      Minnesota Vikings          1961          868
10       Oakland Raiders          1960          879
11    Indianapolis Colts          1953          963
12   Pittsburgh Steelers          1933         1200
13    Kansas City Chiefs          1960          859
14   Washington Redskins          1932         1195
15      Cleveland Browns          1950          937
16    San Diego Chargers          1960          864
17        St. Louis Rams          1937         1128
18      Seattle Seahawks          1976          639
19   Philadelphia Eagles          1933         1180

In [17]:
DataFrame(nfl_frame,columns=['Team','First Season','Total Games','Stadium'])

                    Team  First Season  Total Games  Stadium
0         Dallas Cowboys          1960          894      NaN
1          Chicago Bears          1920         1357      NaN
2      Green Bay Packers          1921         1339      NaN
3         Miami Dolphins          1966          792      NaN
4       Baltimore Ravens          1996          326      NaN
5    San Francisco 49ers          1950         1003      NaN
6   New England Patriots          1960          882      NaN
7        New York Giants          1925         1305      NaN
8         Denver Broncos          1960          874      NaN
9      Minnesota Vikings          1961          868      NaN
10       Oakland Raiders          1960          879      NaN
11    Indianapolis Colts          1953          963      NaN
12   Pittsburgh Steelers          1933         1200      NaN
13    Kansas City Chiefs          1960          859      NaN
14   Washington Redskins          1932         1195      NaN
15      Cleveland Browns          1950          937      NaN
16    San Diego Chargers          1960          864      NaN
17        St. Louis Rams          1937         1128      NaN
18      Seattle Seahawks          1976          639      NaN
19   Philadelphia Eagles          1933         1180      NaN

### Retreiving rows from a Dataframe... to rereive the first top rows use head() and end rows use tail(). By default it is 5 rows for head() and tail()

In [18]:
nfl_frame.head()

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Dallas Cowboys,511,378,6,0.574,1960,894,NFC East
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North

In [19]:
nfl_frame.tail()

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
15,16,Cleveland Browns,469,458,10,0.506,1950,937,AFC North
16,17,San Diego Chargers,428,425,11,0.502,1960,864,AFC West
17,18,St. Louis Rams,552,555,21,0.499,1937,1128,NFC West
18,19,Seattle Seahawks,319,320,0,0.499,1976,639,NFC West
19,20,Philadelphia Eagles,560,594,26,0.486,1933,1180,NFC East

In [21]:
nfl_frame.ix[2]

Rank                            3
Team            Green Bay Packers
Won                           741
Lost                          561
Tied*                          37
Pct.                        0.567
First Season                 1921
Total Games                  1339
Conference              NFC North
Name: 2, dtype: object

In [22]:
nfl_frame['Stadium']="Levi's Stadium"

In [23]:
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference,Stadium
0,1,Dallas Cowboys,511,378,6,0.574,1960,894,NFC East,Levi's Stadium
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North,Levi's Stadium
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North,Levi's Stadium
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East,Levi's Stadium
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North,Levi's Stadium
5,6,San Francisco 49ers,545,444,14,0.550,1950,1003,NFC West,Levi's Stadium
6,7,New England Patriots,478,395,9,0.547,1960,882,AFC East,Levi's Stadium
7,8,New York Giants,691,581,33,0.542,1925,1305,NFC East,Levi's Stadium
8,9,Denver Broncos,464,400,10,0.537,1960,874,AFC West,Levi's Stadium
9,10,Minnesota Vikings,457,401,10,0.532,1961,868,NFC North,Levi's Stadium
10,11,Oakland Raiders,462,406,11,0.532,1960,879,AFC West,Levi's Stadium
11,12,Indianapolis Colts,508,448,7,0.531,1953,963,AFC South,Levi's Stadium
12,13,Pittsburgh Steelers,618,561,21,0.524,1933,1200,AFC North,Levi's Stadium
13,14,Kansas City Chiefs,432,415,12,0.510,1960,859,AFC West,Levi's Stadium
14,15,Washington Redskins,592,576,27,0.507,1932,1195,NFC East,Levi's Stadium
15,16,Cleveland Browns,469,458,10,0.506,1950,937,AFC North,Levi's Stadium
16,17,San Diego Chargers,428,425,11,0.502,1960,864,AFC West,Levi's Stadium
17,18,St. Louis Rams,552,555,21,0.499,1937,1128,NFC West,Levi's Stadium
18,19,Seattle Seahawks,319,320,0,0.499,1976,639,NFC West,Levi's Stadium
19,20,Philadelphia Eagles,560,594,26,0.486,1933,1180,NFC East,Levi's Stadium

In [25]:
len(nfl_frame)

20

In [26]:
nfl_frame['Stadium']=np.arange(20)

In [27]:
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference,Stadium
0,1,Dallas Cowboys,511,378,6,0.574,1960,894,NFC East,0
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North,1
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North,2
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East,3
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North,4
5,6,San Francisco 49ers,545,444,14,0.550,1950,1003,NFC West,5
6,7,New England Patriots,478,395,9,0.547,1960,882,AFC East,6
7,8,New York Giants,691,581,33,0.542,1925,1305,NFC East,7
8,9,Denver Broncos,464,400,10,0.537,1960,874,AFC West,8
9,10,Minnesota Vikings,457,401,10,0.532,1961,868,NFC North,9
10,11,Oakland Raiders,462,406,11,0.532,1960,879,AFC West,10
11,12,Indianapolis Colts,508,448,7,0.531,1953,963,AFC South,11
12,13,Pittsburgh Steelers,618,561,21,0.524,1933,1200,AFC North,12
13,14,Kansas City Chiefs,432,415,12,0.510,1960,859,AFC West,13
14,15,Washington Redskins,592,576,27,0.507,1932,1195,NFC East,14
15,16,Cleveland Browns,469,458,10,0.506,1950,937,AFC North,15
16,17,San Diego Chargers,428,425,11,0.502,1960,864,AFC West,16
17,18,St. Louis Rams,552,555,21,0.499,1937,1128,NFC West,17
18,19,Seattle Seahawks,319,320,0,0.499,1976,639,NFC West,18
19,20,Philadelphia Eagles,560,594,26,0.486,1933,1180,NFC East,19