In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
dframe=pd.read_csv('file1.csv')

In [3]:
dframe

    1        Dallas Cowboys  511  378   6   .574  1960   894   NFC East
0   2         Chicago Bears  752  563  42  0.570  1920  1357  NFC North
1   3     Green Bay Packers  741  561  37  0.567  1921  1339  NFC North
2   4        Miami Dolphins  443  345   4  0.562  1966   792   AFC East
3   5      Baltimore Ravens  182  143   1  0.560  1996   326  AFC North
4   6   San Francisco 49ers  545  444  14  0.550  1950  1003   NFC West
5   7  New England Patriots  478  395   9  0.547  1960   882   AFC East
6   8       New York Giants  691  581  33  0.542  1925  1305   NFC East
7   9        Denver Broncos  464  400  10  0.537  1960   874   AFC West
8  10     Minnesota Vikings  457  401  10  0.532  1961   868  NFC North

In [5]:
dframe=pd.read_csv('file1.csv',header=None)

In [6]:
dframe

    0                     1    2    3   4      5     6     7          8
0   1        Dallas Cowboys  511  378   6  0.574  1960   894   NFC East
1   2         Chicago Bears  752  563  42  0.570  1920  1357  NFC North
2   3     Green Bay Packers  741  561  37  0.567  1921  1339  NFC North
3   4        Miami Dolphins  443  345   4  0.562  1966   792   AFC East
4   5      Baltimore Ravens  182  143   1  0.560  1996   326  AFC North
5   6   San Francisco 49ers  545  444  14  0.550  1950  1003   NFC West
6   7  New England Patriots  478  395   9  0.547  1960   882   AFC East
7   8       New York Giants  691  581  33  0.542  1925  1305   NFC East
8   9        Denver Broncos  464  400  10  0.537  1960   874   AFC West
9  10     Minnesota Vikings  457  401  10  0.532  1961   868  NFC North

In [8]:
dframe=pd.read_table('file1.csv',sep=',',header=None)

In [9]:
dframe

    0                     1    2    3   4      5     6     7          8
0   1        Dallas Cowboys  511  378   6  0.574  1960   894   NFC East
1   2         Chicago Bears  752  563  42  0.570  1920  1357  NFC North
2   3     Green Bay Packers  741  561  37  0.567  1921  1339  NFC North
3   4        Miami Dolphins  443  345   4  0.562  1966   792   AFC East
4   5      Baltimore Ravens  182  143   1  0.560  1996   326  AFC North
5   6   San Francisco 49ers  545  444  14  0.550  1950  1003   NFC West
6   7  New England Patriots  478  395   9  0.547  1960   882   AFC East
7   8       New York Giants  691  581  33  0.542  1925  1305   NFC East
8   9        Denver Broncos  464  400  10  0.537  1960   874   AFC West
9  10     Minnesota Vikings  457  401  10  0.532  1961   868  NFC North

In [10]:
pd.read_csv('file1.csv',sep=',',header=None,nrows=5)

   0                  1    2    3   4      5     6     7          8
0  1     Dallas Cowboys  511  378   6  0.574  1960   894   NFC East
1  2      Chicago Bears  752  563  42  0.570  1920  1357  NFC North
2  3  Green Bay Packers  741  561  37  0.567  1921  1339  NFC North
3  4     Miami Dolphins  443  345   4  0.562  1966   792   AFC East
4  5   Baltimore Ravens  182  143   1  0.560  1996   326  AFC North

In [11]:
dframe.to_csv('mytextdata_out.csv')